### ISSUE TITLE
[Wishes] getatime and getmtime functions

### ISSUE THREAD

**Issue by kasru** [keplerproject/luafilesystem#100]
Please add 2 functions to luafilesystem

lfs.getatime(path) -> Return the time of last access of path. 
lfs.getmtime(path) -> Return the time of last modification of path.

**Comment by hishamhm** [comment]
You'll be happy to learn that this functionality is already available:

```
lfs.attributes(filename, "access")
lfs.attributes(filename, "modification")
```

Cheers!
