### ISSUE TITLE
attributes(file) returns nil for files on Mac

### ISSUE THREAD

**Issue by drauschenbach** [keplerproject/luafilesystem#104]
I'm iterating a directory on a Mac running Lua 5.2.4.

```lua
for file in lfs.dir('fixtures') do
  local attr = lfs.attributes(file)
end
```

The returned `attr` is fully populated for directories [`.` and `..`], but nil for the file in my directory.

I don't think there's anything special about the file in my directory:

```sh
$ ls -al
total 8
drwxr-xr-x   3 davidr  admin  102 Aug 11 20:06 .
drwxr-xr-x  21 davidr  admin  714 Dec 10 07:09 ..
-rw-r--r--   1 davidr  admin   48 Aug 11 20:06 aristotle1.txt
```

So as far as I can tell,`lfs.attribute()` is completely broken on a Mac.

**Comment by mpeterv** [comment]
`lfs.dir` iterates over names of files and directories, while `lfs.attributes` accepts paths. There is a difference if using `lfs.dir` on a directory other than current one. E.g. in your snippet `lfs.dir` returns `aristotle1.txt`, and then its passed to `lfs.attributes`, while the proper relative path is `fixtures/aristotle1.txt`.

The solution is to join names returned by `lfs.dir` iterator with some prefix to get complete paths:

```lua
for file in lfs.dir('fixtures') do
   local attr = lfs.attributes('fixtures/' .. file)
end
```
