### ISSUE TITLE
Is there any way to change LUA_INC  and LUA_LIBDIR?

### ISSUE THREAD

**Issue by GhostZCH** [keplerproject/luafilesystem#111]
We need to make this lib use luajit libs and header files not in the system paths, is there any way to change LUA_INC and LUA_LIBDIR?

Thank you!

**Comment by hishamhm** [comment]
If using LuaRocks, this is easy:

To use a LuaJIT installed in `/your/path`, do `luarocks install luafilesystem LUA_INCDIR=/your/path/include LUA_LIBDIR=/your/path/lib`

To make these permanent, add `variables.LUA_INCDIR=/your/path/include; variables.LUA_LIBDIR=/your/path/lib` to your LuaRocks config file (run `luarocks` with no arguments to see where that file is in your platform).

Ideally, you should give the paths to your LuaJIT headers and libraries when installing LuaRocks, to make these settings automatic.

**Comment by GhostZCH** [comment]
@hishamhm thank you, i will try it
