### ISSUE TITLE
The "lfs.lua" module is not installed or compiled

### ISSUE THREAD

**Issue by M1que4s** [keplerproject/luafilesystem#112]
Well ... the problem is this:

**using luarocks (even compiling the code from the repository) only the shared library (lfs.so) is installed, but the module for development, that is, the file used through the "require" function, is not installed by any of the two methods.**

please, is there any solution?

**It is worth noting that this error presents me in version 1.7.0-2. I previously installed lfs and this problem did not happen to me**

**Comment by hishamhm** [comment]
@M1que4s you might be missing the LuaRocks paths in your environment. Run `eval $(luarocks path)` in your shell and then try `require("lfs")` from Lua again.

**Comment by M1que4s** [comment]
Well, I understand what they say, but the problem is that in previous versions if I could use lfs loading a .lua file and from there I could use it through a variable, but the problem is that lua just does not load the lfs.so file, even if everything is correct

**Comment by Tieske** [comment]
what does your Lua code look like, can yu poist a minimal case showing the behaviour (including full error output)
