### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by wbtlb** [keplerproject/luafilesystem#113]
after using make to compile lfs module, i get an error.

# cat test.lua
package.cpath = "/test/?.so" 
local lfs = require "lfs"
lfs.mkdir("./ttt")

output:
lua: error loading module 'lfs' from file '/test/lfs.so':
	/test/lfs.so: undefined symbol: luaL_setfuncs
stack traceback:
	[C]: ?
	[C]: in function 'require'
	t.lua:2: in main chunk
	[C]: ?

**Comment by hishamhm** [comment]
this is a mixup between Lua versions (for example, you compiled with headers for Lua 5.x and are loading it from Lua 5.y)
