### ISSUE TITLE
Refresh/update the online documentation

### ISSUE THREAD

**Issue by tst2005** [keplerproject/luafilesystem#115]
Hello,

The last year, I made a little contribution about the documentation (see https://github.com/keplerproject/luafilesystem/pull/106 ) merged into master.

The online documentation https://keplerproject.github.io/luafilesystem/manual.html#attributes stay the same.

* Is it possible to update it ?

The LFS (online) documentation is took as the standard API to follow.
It will help me to contribute to an alternative LFS compatible implementation.

Regards,

**Comment by hishamhm** [comment]
@tst2005 hi, I'm pretty swamped this week, could you send a PR to the `gh-pages` branch to synchronize with the `master` docs? that will update the public docs

**Comment by tst2005** [comment]
@hishamhm done https://github.com/keplerproject/luafilesystem/pull/116

**Comment by tst2005** [comment]
@hishamhm can you consider my PR #116  ? thanks

**Comment by tst2005** [comment]
The documentation has been updated. Thanks!
