### ISSUE TITLE
dir does not work on win32?

### ISSUE THREAD

**Issue by subsoap** [keplerproject/luafilesystem#129]
With Defold we use this https://github.com/britzl/defold-lfs identical code, and dir does not work on a win32 build. Might be related to building with Clang 9?

**Comment by hishamhm** [comment]
@subsoap unfortunately I wouldn't know. AFAICT dir works on lfs on Windows. You may want to open a bug report in that repository instead?

**Comment by subsoap** [comment]
Solution for issue in Defold's case ![issue](https://user-images.githubusercontent.com/409170/66891003-ccb71d00-ef9c-11e9-9536-e1ca72d90a48.png)
