### ISSUE TITLE
Upload new dev-rockspec to LuaRocks.org

### ISSUE THREAD

**Issue by siffiejoe** [keplerproject/luafilesystem#150]
The latest dev rockspec on LuaRocks.org is cvs-4 from 5 years ago. There is also a corresponding source rock for that version, so all dev installations use obsolete source code. This leads to build failures for Lua 5.4 since the old source code didn't support that Lua version (but the rockspec incorrectly claims "lua >= 5.1").

See [this stackoverflow question](https://stackoverflow.com/questions/67528613/cannot-install-penlight-unsupported-lua-version).

**Comment by hishamhm** [comment]
dev rockspecs shouldn't include src.rock entries in the repo, that's the
problem. The current dev rockspec itself should be fine, right?

**Comment by siffiejoe** [comment]
The scm-1 rockspec in the repository works fine for Lua 5.1 - 5.4 on Linux.

**Comment by hishamhm** [comment]
I have deleted the src.rock file that was in the repo (oddly, it listed 0 downloads).

**Comment by hishamhm** [comment]
cvs-4 looks identical to scm-1, so I think this should be good to close. Feel free to reopen if there are still any problems. Thanks for bringing it up!
