### ISSUE TITLE
don't support use "~"

### ISSUE THREAD

**Issue by blakejia** [keplerproject/luafilesystem#51]
This is my test program.
> print((require "lfs").attributes("~", "mode"))
nil     cannot obtain information from file `~'
> print((require "lfs").attributes(".", "mode"))
directory

I use OS is Mac 10.10

**Comment by hishamhm** [comment]
"." and ".." a file-system level concept, handled by the OS calls.
"~" is a shell-level concept, handled by your shell's argument parser.

Use `os.getenv("HOME")` instead.
