### ISSUE TITLE
Does LFS works with lua 5.2.3?

### ISSUE THREAD

**Issue by rscarrasco** [keplerproject/luafilesystem#58]
I installed LFS via luarocks, and then executed `require 'lfs'` on the interpreter, and that is what I got:

    version mismatch: app. needs 503, Lua core provides 502
    stack traceback:
	    [C]: in ?
	    [C]: in function 'require'
	    stdin:1: in main chunk
	    [C]: in ?

I don't know what these numbers mean, but the `version mismatch` struck a cord in my head. Does LFS works with lua 5.2.3?

I use Linux Mint 17.3.

**Comment by ignacio** [comment]
Hi Rafael. It should work with no problems, yes. This is a mismatch between the Lua version used by LuaRocks and the Lua version of your interpreter.

By the numbers (502 and 503), it seems that you are mixing Lua 5.3 with Lua 5.2

**Comment by rscarrasco** [comment]
Oh, Lua 5.3? That is weird...

    lua -v
    Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio

And `luarocks` says

    LuaRocks 2.3.0, a module deployment system for Lua
    
    ...
    
    CONFIGURATION
        Lua version: 5.2
    ...

Am I missing something?

**Comment by hishamhm** [comment]
What about your `lua.h` headers? Maybe you have a `devel` package for Lua 5.3 installed?

Check the version of Lua reported in your `lua.h` file.

**Comment by rscarrasco** [comment]
The headers were really from Lua 5.3... I fixed it, and now it works. Thanks!
