### ISSUE TITLE
Missing documentation for attributes.permissions

### ISSUE THREAD

**Issue by MisterDA** [keplerproject/luafilesystem#59]
The [`permissions`](https://github.com/keplerproject/luafilesystem/blob/master/src/lfs.c#L802) field is not documented in the manual.

**Comment by hishamhm** [comment]
I think "permissions" is supported only in Unix. If that's the case, it should be documented...

**Comment by ignacio** [comment]
It is supported on [Windows as well](https://github.com/keplerproject/luafilesystem/blob/master/src/lfs.c#L748).

@MisterDA both pull requests seems equal. Can you drop one of them?

**Comment by MisterDA** [comment]
Oh yeah but I've made one for the [master](#60) branch and the other for the [gh-pages](#61) branch (It's just a cherry-pick). I don't know how you keep them both synced. My PR is really simple, does the field needs more explanations ?

**Comment by ignacio** [comment]
Thank you! I think no more explanations are needed.
