### ISSUE TITLE
Unused static int pushresult() on Windows

### ISSUE THREAD

**Issue by n1tehawk** [keplerproject/luafilesystem#65]
When using more strict checking (e.g. `-Wall` or `-Wunused-function`) on platforms where `_WIN32` is defined, the compiler may complain:
```
lfs.c:152:12: warning: ‘pushresult’ defined but not used [-Wunused-function]
 static int pushresult(lua_State *L, int i, const char *info)
            ^
```
This is due to the fact that `make_link()` won't use `pushresult()` and will always fail with `pusherror()` instead.

It might be desirable to either
a) encapsulate the `pushresult` declaration with a `#ifndef _WIN32` / `#endif` block, or
b) change the `pusherror(L, "make_link is not supported on Windows");` to `pushresult(L, -1, "make_link is not supported on Windows");` instead.
(I actually prefer the latter.)

[EDIT] An assignment like `errno = ENOSYS;` could also be a good idea, so the subsequent `strerror(errno)` returns something meaningful.

Regards, NiteHawk

**Comment by hishamhm** [comment]
Could you send in a pull request with either solution? I currently have no way to test this on Windows. Thanks!

**Comment by n1tehawk** [comment]
In my [private branch](https://github.com/n1tehawk/luafilesystem/commits/nitehawk) I have added a diagnostic `#pragma` to demonstrate the problem on Appveyor CI - see e.g. https://ci.appveyor.com/project/n1tehawk/luafilesystem/build/0.0.1.6-test. The pull request is based on the separate [contrib](https://github.com/n1tehawk/luafilesystem/commits/contrib) branch, and contains only the fix.

Regards, NiteHawk

**Comment by n1tehawk** [comment]
Is there a problem with this pull request, or is anything unclear?

**Comment by mpeterv** [comment]
Why are these helper functions not used in other places? Functions from standard IO library return (nil, errormsg, errno) on error where errormsg is `strerror(errno)` or `filename: strerror(errno)` when there is a related file. It would make sense to use `pushresult` which does something similar in all LFS functions, not just `link`.

**Comment by hishamhm** [comment]
@n1tehawk merged, thank you!

@mpeterv I have no idea, I never studied the LuaFileSystem codebase in detail, but perhaps @tomasguisasola is able to answer that.
