### ISSUE TITLE
Handling of second argument of lfs.attributes

### ISSUE THREAD

**Issue by mpeterv** [keplerproject/luafilesystem#72]
There is a feature that I think is not documented: if a table is passed to `lfs.attributes` as the second argument, it is filled with attributes instead of a new table. Otherwise if the second argument is not a string it is ignored. Should this be mentioned in the docs or removed?

**Comment by hishamhm** [comment]
I would document this:
"if a table is passed to lfs.attributes as the second argument, it is filled with attributes instead of a new table."
But would leave this unspecified to avoid blocking future extensions: 
"Otherwise if the second argument is not a string it is ignored."

**Comment by mpeterv** [comment]
Done in @03e01ff
