### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by mpeterv** [keplerproject/luafilesystem#75]
I think there are enough small fixes for 1.6.3 to justify a new patch release.

**Comment by mpeterv** [comment]
Since #78 has been merged into master, the next version will be 1.7. Need to merge existing 1.7 branch into master.

**Comment by mpeterv** [comment]
@hishamhm I've merged 1.7 into master and prepared changelog for the new version in the docs.

**Comment by hishamhm** [comment]
Done! (A day late)
