### ISSUE TITLE
manual ancor mistake

### ISSUE THREAD

**Issue by tst2005** [keplerproject/luafilesystem#77]
Hello,

I don't know if the `https://keplerproject.github.io/luafilesystem/manual.html` page is generated but there are some little mistake in the section ancor names.

* [x] `lfs.chdir`is ok with [manual.html#chdir](https://keplerproject.github.io/luafilesystem/manual.html#chdir)
* [ ] `lfs.currentdir` is `manual.html#getcwd` should be [manual.html#currentdir](https://keplerproject.github.io/luafilesystem/manual.html#currentdir)
* [ ]  `lfs.lock_dir` is `manual.html#chdir` should be [manual.html#lock_dir](https://keplerproject.github.io/luafilesystem/manual.html#lock_dir)
* [x] `lfs.dir` is ok with [manual.html#dir](https://keplerproject.github.io/luafilesystem/manual.html#dir)
* [x] all others seems also ok.

The source code :
```html
<dt><a name="chdir"></a><strong><code>lfs.chdir (path)</code></strong></dt>
...
<dt><a name="chdir"></a><strong><code>lfs.lock_dir(path, [seconds_stale])</code></strong></dt>
...
<dt><a name="getcwd"></a><strong><code>lfs.currentdir ()</code></strong></dt>
...
<dt><a name="dir"></a><strong><code>iter, dir_obj = lfs.dir (path)</code></strong></dt>
```

Regards,

**Comment by hishamhm** [comment]
it's done by hand! PRs fixing the `doc` subdir and the `gh-pages` branch would be most welcome!

**Comment by mpeterv** [comment]
Fixed.
