### ISSUE TITLE
Release for 1.6.3 has an extra '_' between the 'v' and the '1'.

### ISSUE THREAD

**Issue by hartzell** [keplerproject/luafilesystem#88]
Not sure if this was done intentionally for some reason, but the tag for `1_6_3` has an extra `_` in it's name between the `v` and the `1`

```
v_1_6_3
```

I noticed this because it [breaks some of the automation](https://github.com/LLNL/spack/issues/2682) in the [Spack](https://github.com/llnl/spack) package manager.

**Comment by hishamhm** [comment]
Tags haven't been super consistent over the years (just noticed `v1.5.0` there too). Would adding a `v1_6_3` tag suffice for your needs?

**Comment by hartzell** [comment]
Yes, that's what Spack's automagic machinery expects so builds will work smoothly.

**Thanks!!**

**Comment by hishamhm** [comment]
Done! Have a great day. :)

**Comment by hartzell** [comment]
Perfect!
