### ISSUE TITLE
just curious about tag name

### ISSUE THREAD

**Issue by tst2005** [keplerproject/luafilesystem#90]
I see on this repository (and also others) some tag named "v1_2_3" or "v_1_2_3" instead of "v1.2.3".
Somebody know the reason ?

Regards,

**Comment by tomasguisasola** [comment]
Hi TsT

On 2017-03-16 10:18, TsT wrote:
> I see on this repository (and also others) some tag named "v1_2_3" or
> "v_1_2_3" instead of "v1.2.3".
>  Somebody know the reason ?
I am not sure, but IRC old CVS systems didn't allow dots in tag names.

Regards,
Tomás

**Comment by hishamhm** [comment]
Yes, it's because the repo was converted from CVS.
