### ISSUE TITLE
Installation fails, cannot find errno.h

### ISSUE THREAD

**Issue by birgersp** [keplerproject/luafilesystem#91]
Windows 10, installed Visual Studio 10, added cl.exe to PATH.

(If it matters) cl.exe directory: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64`

```
C:\Windows\system32>luarocks install luafilesystem
Installing http://luarocks.org/repositories/rocks/luafilesystem-1.6.3-2.src.rock...
cl /MD /O2 -c -Fosrc/lfs.obj -IC:/Program Files (x86)/Lua/5.1/include src/lfs.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

lfs.c
src/lfs.c(37): fatal error C1083: Cannot open include file: 'errno.h': No such file or directory

Error: Build error: Failed compiling object src/lfs.obj
```

**Comment by purplepwny** [comment]
You need to install the Windows 10 SDK component of Visual Studio, as it contains the C runtime that provides errno.h.

**Comment by birgersp** [comment]
I've installed Windows 10 SDK now, and I can see `errno.h` is located here:
`C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt`

Still getting the same error

**Comment by purplepwny** [comment]
You should run `luarocks install` from the Developer Command Prompt for Visual Studio. You have errno.h now, but it's not being picked up by CL because it's not in your include path. Developer command prompt will set that up for you.

**Comment by birgersp** [comment]
That gave me some progress. Seems I had an erroneous/half-completed installation of luafilesystem. Reinstalled lua and luarocks. Tried running `luarocks install luafilesystem` again but now it's complaining about my "machine type".

```
C:\Program Files (x86)\Lua\5.1\lib\lua5.1.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x86\uuid.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\lib\x86\MSVCRT.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
lfs.dll : fatal error LNK1120: 63 unresolved externals

Error: Build error: Failed installing lfs.dll in C:\Program Files (x86)\Lua\5.1\rocks/luafilesystem/1.6.3-2/lib
```

**Comment by purplepwny** [comment]
It looks like it's trying to link 32 bit libs into what is otherwise a 64 bit build of luafilesystem--not familiar enough w/ luarocks or the Microsoft toolchain to know why. You should try using the version of Lua that comes with luarocks by specifying /L to the luarocks install script. That's what worked for me.

**Comment by Bulat-Ziganshin** [comment]
you probably started default MSVC command prompt that is 64-bit. look into "visual studio 2015" folder in main programs menu and find there x86 command prompt. or just start simple cmd and run of the following commands, depending on your msvc version:
```
call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
```
(disclaimer: i know nothing about luarocks, but sure it's a way to setup msvc x86 compilation environment which i use a lot)

**Comment by birgersp** [comment]
Solved!

(I hate using Windows)

Thanks guys
